MIN_CHROME_VERSION = 110
CHROME_VERSION = max(120, MIN_CHROME_VERSION)
IMPERSONATE_PROFILE = f"chrome{CHROME_VERSION}"
USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    f"Chrome/{CHROME_VERSION}.0.0.0 Safari/537.36"
)
